config/routes.rb
Tarzan::Application.routes.draw do

  root :to => 'articles#index'

  match 'feed' => 'articles#list', :format => :rss
  match 'articles/rss.xml', :to => redirect('/feed')
  match 'articles/atom.xml', :to => redirect('/feed')

  match 'articles/:slug' => 'articles#show'
  match 'articles' => 'articles#list'

  match 'previews/:slug' => 'previews#show'
  match 'previews' => 'previews#index'
  match 'reload' => 'previews#reload'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :markdown
  def markdown(string)
    RDiscount.new(string).to_html.html_safe
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @page_title = ''
    @article = Blog.cover_article
    render @article.present? ? :show : :index
  end

  def list
    @articles = Blog.feed
    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end

  def show
    @article = Blog.fetch_article(params[:slug].to_s.parameterize)
    raise ActiveRecord::RecordNotFound unless @article.present?
  end

end

app/controllers/previews_controller.rb
class PreviewsController < ApplicationController

  http_basic_authenticate_with :name => BLOG_USER, :password => BLOG_PASSWORD

  def index
    @previews = Blog.preview_feed
    @drafts = Blog.draft_feed
  end

  def show
    @article = Blog.preview_article(params[:slug].to_s.parameterize)
    raise ActiveRecord::RecordNotFound unless @article.present?
    render 'articles/show'
  end

  def reload
    Blog.refresh_articles
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title
    prefix = @page_title || content_for(:page_title)
    [prefix, site_title].reject(&:blank?).compact.join(' - ')
  end

  def site_title
    BLOG_TITLE
  end

  def site_description
    BLOG_DESCRIPTION
  end

  def site_subtitle
    BLOG_SUBTITLE
  end

  def article_date
    return "" unless @article.present?
    tag(:meta, :name => "publication-date", :value => @article.published_on)
  end

end

app/helpers/article_helper.rb
module ArticleHelper

  def format_article(article)
    case article.format
      when '.markdown', '.md' then markdown(article.content)
      else article.content
    end
  end

  def article_style(article)
    article.style.to_s.downcase.to_param
  end

end

app/helpers/url_helper.rb
module UrlHelper

  def site_url
    BLOG_URL
  end

  def full_article_url(article)
    "#{site_url}#{article_url article}"
  end

  def article_url(article)
    prefix = article.published? ? 'articles' : 'previews'
    "/#{prefix}/#{article.slug}"
  end

end

app/views/articles/_article.html.erb
<li class="<%= article_style article %>">
  <span class="date"><%= article.published_on %></span>
  <span class="title"><%= link_to article.title, article_url(article) %></span>
</li>

app/views/articles/list.html.erb
<% content_for :page_title, 'Articles' %>

<div class="header">
  <h1>Articles</h1>
</div>

<div class="article listing">
  <ul>
    <%= render :partial => 'article', :collection => @articles, :as => :article %>
  </ul>
</div>

app/views/articles/show.html.erb
<% content_for :page_title, @article.title.html_safe %>

<div class="header">
  <h1><%= link_to @article.title, article_url(@article) %></h1>
</div>
<div class="article <%= article_style @article %>">
  <%= format_article @article %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>

  <%= stylesheet_link_tag "application", media: "all" %>

  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag :rss, feed_url(:format => "rss") %>
  <%= article_date %>

  <meta name="viewport" content="initial-scale = 1.0">
  <meta name="description" content="<%= site_description %>" />
</head>

<body>

  <div class="title header">
    <h1><%= link_to site_title, root_url %></h1>
    <p><%= site_subtitle %></p>
  </div>

  <div class="stage">
    <%= yield %>
  </div>

  <div class="footer">
    <div class="navigation">
      <%= link_to "articles", articles_url %>
    </div>
  </div>

</body>
</html>

app/views/previews/index.html.erb
<% content_for :page_title, 'Previews & Drafts'.html_safe %>

<div class="header">
  <h1>Previews &amp; Drafts</h1>
</div>

<div class="article listing">
  <h2>Previews</h2>
  <ul>
    <%= render :partial => 'articles/article', :collection => @previews, :as => :article %>
  </ul>
  <h2>Drafts</h2>
  <ul>
    <%= render :partial => 'articles/article', :collection => @drafts, :as => :article %>
  </ul>
</div>

app/views/previews/reload.html.erb
<% content_for :page_title, 'RELOADED' %>

<div class="header">
  <h1>RELOADED</h1>
</div>